import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase/client';

export async function POST(req: Request) {
    try {
        const { companies } = await req.json();

        if (!Array.isArray(companies) || companies.length === 0) {
            return NextResponse.json({ error: 'Invalid data' }, { status: 400 });
        }

        // Insert into Supabase
        // Note: companies array keys must match table column names
        const { data, error } = await supabase
            .from('companies')
            .upsert(companies, { onConflict: 'id' }) // or 'company_name' if we want unique names, but 'id' needs to be present or autogenerated. 
            // If CSV doesn't have ID, we should let DB generate it. Upsert with no ID acts as Insert.
            .select();

        if (error) {
            console.error('Import error:', error);
            return NextResponse.json({ error: error.message }, { status: 500 });
        }

        return NextResponse.json({ count: companies.length, success: true });
    } catch (error) {
        console.error('Server error:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
